name: Python tests

on: [push]

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install ruff
          pip install poetry==1.8.3
          poetry config virtualenvs.create false
          poetry install
      - name: Lint
        continue-on-error: true #FIXME remove when tests implemented
        run: ruff check --output-format=github .
      - name: Test
        continue-on-error: true #FIXME remove when tests implemented
        run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
