name: Python package

on: [push]

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox-gh>=1.2
          #pip install pytest
          pip install .
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox --skip-pkg-install
      #- name: Test
        #run: pytest tests.py --doctest-modules --junitxml=junit/test-results-${{ env.PYTHON_VERSION }}.xml
      #- name: Upload pytest test results
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: pytest-results-${{ env.PYTHON_VERSION }}
      #    path: junit/test-results-${{ env.PYTHON_VERSION }}.xml
      #  # Use always() to always run this step to publish test results when there are test failures
      #  if: ${{ always() }}

  release-build:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install .
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
