name: Python tests

on: [push]

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing

    services:
      postgres:
        image: citusdata/citus:12.1
        env:
          POSTGRES_PASSWORD:  secret
          POSTGRES_USER:      user
          POSTGRES_DB:        nightcrawler
          POSTGRES_PORT:      5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    steps:
      - name: Create storage containers
        run: |
          for blob in images processing public;do docker run --rm --network host mcr.microsoft.com/azure-cli az storage container create -n ${blob} --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;";done;
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install ruff
          pip install poetry==1.8.3
          poetry config virtualenvs.create false
          poetry install
      - name: Lint
        run: ruff check --output-format=github .
      - name: Typing
        run: python -m mypy --ignore-missing-imports  libnightcrawler tests
      - name: Test
        run: pytest --junitxml=junit/test-results.xml --cov=libnightcrawler --cov-report=xml --cov-report=html
