name: Python tests

on: [push]

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD:  secret
          POSTGRES_USER:      user
          POSTGRES_DB:        nightcrawler
          POSTGRES_PORT:      5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install ruff
          pip install poetry==1.8.3
          poetry config virtualenvs.create false
          poetry install
      - name: Lint
        run: ruff check --output-format=github .
      - name: Test
        run: pytest --junitxml=junit/test-results.xml --cov=libnightcrawler --cov-report=xml --cov-report=html
